#ifndef _XSAVE_ASM_H_
#define _XSAVE_ASM_H_

/* Address to store the register values following the start-up/INIT */
#define XSAVE_STARTUP_XCR0_LOW_ADDR		0x8000U
#define XSAVE_STARTUP_XCR0_HI_ADDR		(XSAVE_STARTUP_XCR0_LOW_ADDR + 4U)

#define XSAVE_STARTUP_XCR1_LOW_ADDR		(XSAVE_STARTUP_XCR0_HI_ADDR + 4U)
#define XSAVE_STARTUP_XCR1_HI_ADDR		(XSAVE_STARTUP_XCR1_LOW_ADDR + 4U)

#define XSAVE_STARTUP_CR4_ADDR			(XSAVE_STARTUP_XCR1_HI_ADDR + 4U)

#define XSAVE_INIT_CR4_ADDR			(XSAVE_STARTUP_CR4_ADDR + 8U)
#define XSAVE_XCR0_LOW				(XSAVE_INIT_CR4_ADDR + 4U)
#define XSAVE_XCR0_HIGH				(XSAVE_XCR0_LOW + 4U)

#define XSAVE_XCR1_LOW				(XSAVE_XCR0_HIGH + 4U)
#define XSAVE_XCR1_HIGH				(XSAVE_XCR1_LOW + 4U)
#endif
