#!/bin/bash
# usage: usage: grub_iso <file.iso> <kernels ...>
# descr: generate a bootable iso with grub + kernel files
# author: Salva Peiro <speiro@ai2.upv.es>

function warn() { echo -e $* 1>&2; }
function usage(){ echo "usage: $(basename $0) <file.iso> <kernels ...>"; }

if test -z "$*"; then
	warn `usage`
	exit
fi

# user configurable variables
isodir=`mktemp -d /tmp/iso.XXX`
isofile=file.iso
default=0
timeout=4

while getopts t:d: c
do
    case $c in
    t)  timeout="$OPTARG";;
    d)  default="$OPTARG";;
    ?)  usage; exit 2;;
    esac
done
shift $(($OPTIND - 1))

mkdir -p $isodir/boot/grub
if test $# -gt 1; then
	isofile=$1; shift
fi

# generate a proper menu.lst
(
	echo    set default=$default
	echo    set timeout=$timeout
	echo    menuentry 'acrn unit test elf file' {
	echo    echo 'Load unit test ...'
	for f in $*; do
		if test -f $f; then
			cp $f $isodir/boot/grub/
			fname=`basename $f`
			echo    multiboot /boot/grub/`basename $f`
		fi
	done
	echo    }
) > $isodir/boot/grub/grub.cfg

if [ -z "`dpkg -l xorriso`" ]; then
    echo "WARNING: Please install necessary package xorriso firstly!!"
fi
if [ -z "`dpkg -l grub-pc-bin`" ]; then
    echo "WARNING: Please install necessary package grub-pc-bin firstly for UEFI machine!!"
fi

if which grub-mkrescue; then
    grub-mkrescue -o $isofile $isodir
elif which grub2-mkrescue; then
    grub2-mkrescue -o $isofile $isodir
fi

rm -r $isodir
