#ifndef __IDLE_BLOCK_H__
#define __IDLE_BLOCK_H__

#define CPUID_1_ECX_MONITOR		(1U << 3)
#define CPUID_5_ECX_MONITOR_EXTEN	(1U << 0)

#define IA32_MISC_ENABLE_STARTUP_ADDR	(0x6000)
#define IA32_MISC_ENABLE_INIT1_ADDR	(0x8000)
#define ENABLE_MONITOR_FSM_BIT		(1UL << 18)

#define IA32_MONITOR_FILTER_SIZE_STARTUP_ADDR (0x6008)
#define IA32_MONITOR_FILTER_SIZE_INIT_ADDR (0x8008)
#endif
