#ifndef __LOCAL_APIC_H__
#define __LOCAL_APIC_H__
#define APIC_CMCI						0x2F0
#define LAPIC_REG_OFFSET				0x100
#define	LAPIC_STARTUP_BASE_ADDR			0x6000
#define	LAPIC_INIT_BASE_ADDR			0x7000
#define	LAPIC_UNCHANGED_BASE_ADDR		0x8000
#define LAPIC_STARTUP_REG_BASE_ADDR		(0x6000 + (LAPIC_REG_OFFSET))
#define LAPIC_INIT_REG_BASE_ADDR		(0x7000 + (LAPIC_REG_OFFSET))
#define LAPIC_UNCHANGED_REG_BASE_ADDR	(0x8000 + (LAPIC_REG_OFFSET))
#define LAPIC_STARTUP_REG_ADDR(reg)		(LAPIC_STARTUP_REG_BASE_ADDR + (reg))
#define LAPIC_INIT_REG_ADDR(reg)		(LAPIC_INIT_REG_BASE_ADDR + (reg))
#define LAPIC_UNCHANGED_REG_ADDR(reg)	(LAPIC_UNCHANGED_REG_BASE_ADDR + (reg))
/* following INIT registers address*/
#define IA32_APIC_BASE_INIT_ADDR	(LAPIC_INIT_BASE_ADDR)
#define LVT_CMCI_INIT_ADDR			(IA32_APIC_BASE_INIT_ADDR + 4)
#define LINT0_INIT_ADDR				(LVT_CMCI_INIT_ADDR + 4)
#define LINT1_INIT_ADDR				(LINT0_INIT_ADDR + 4)
#define LVT_ERROR_INIT_ADDR			(LINT1_INIT_ADDR + 4)
#define LVTTHMR_INIT_ADDR			(LVT_ERROR_INIT_ADDR + 4)
#define LVTPC_INIT_ADDR				(LVTTHMR_INIT_ADDR +  4)
#define LVT_TIMER_INIT_ADDR			(LVTPC_INIT_ADDR + 4)
#define ESR_INIT_ADDR				(LVT_TIMER_INIT_ADDR + 4)
#define SVR_INIT_ADDR				(ESR_INIT_ADDR + 4)
#define ICR_INIT_ADDR				(SVR_INIT_ADDR + 4)
#define TPR_INIT_ADDR				(ICR_INIT_ADDR + 4)
#define PPR_INIT_ADDR				(TPR_INIT_ADDR + 4)
#define IRR_INIT_ADDR				(PPR_INIT_ADDR + 4)
#define ISR_INIT_ADDR				(IRR_INIT_ADDR + 4)
#define TMR_INIT_ADDR				(ISR_INIT_ADDR + 4)
#define CR8_INIT_ADDR				(TMR_INIT_ADDR + 4)
#define TICR_INIT_ADDR				(CR8_INIT_ADDR + 8)
#define TCCR_INIT_ADDR				(TICR_INIT_ADDR + 4)
#define TDCR_INIT_ADDR				(TCCR_INIT_ADDR + 4)
#define IA32_TSC_DEADLINE_INIT_ADDR	(TDCR_INIT_ADDR + 4)

/*startup registers address*/
#define IA32_APIC_BASE_STARTUP_ADDR		(LAPIC_STARTUP_BASE_ADDR)
#define LVT_CMCI_STARTUP_ADDR			(IA32_APIC_BASE_STARTUP_ADDR + 4)
#define LINT0_STARTUP_ADDR				(LVT_CMCI_STARTUP_ADDR + 4)
#define LINT1_STARTUP_ADDR				(LINT0_STARTUP_ADDR + 4)
#define LVT_ERROR_STARTUP_ADDR			(LINT1_STARTUP_ADDR + 4)
#define LVT_THMR_STARTUP_ADDR			(LVT_ERROR_STARTUP_ADDR + 4)
#define LVT_PCR_STARTUP_ADDR			(LVT_THMR_STARTUP_ADDR + 4)
#define LVT_TIMER_STARTUP_ADDR			(LVT_PCR_STARTUP_ADDR + 4)
#define ESR_STARTUP_ADDR				(LVT_TIMER_STARTUP_ADDR + 4)
#define SVR_STARTUP_ADDR				(ESR_STARTUP_ADDR + 4)
#define ICR_STARTUP_ADDR				(SVR_STARTUP_ADDR + 4)
#define TPR_STARTUP_ADDR				(ICR_STARTUP_ADDR + 4)
#define PPR_STARTUP_ADDR				(TPR_STARTUP_ADDR + 4)
#define IRR_STARTUP_ADDR				(PPR_STARTUP_ADDR + 4)
#define ISR_STARTUP_ADDR				(IRR_STARTUP_ADDR + 4)
#define TMR_STARTUP_ADDR				(ISR_STARTUP_ADDR + 4)
#define CR8_STARTUP_ADDR				(TMR_STARTUP_ADDR + 8)
#define TICR_STARTUP_ADDR				(CR8_STARTUP_ADDR + 4)
#define TCCR_STARTUP_ADDR				(TICR_STARTUP_ADDR + 4)
#define DCR_STARTUP_ADDR				(TCCR_STARTUP_ADDR + 4)
#define IA32_TSC_DEADLINE_STARTUP_ADDR	(DCR_STARTUP_ADDR + 4)

#define MSR_APIC_CMCI					0x82F
#define MSR_APIC_LVT0					0x835
#define MSR_APIC_LVT1					0x836
#define MSR_APIC_LVTERR					0x837
#define MSR_APIC_LVTTHMR				0x833
#define MSR_APIC_LVTPC					0x834
#define MSR_APIC_LVTT					0x832
#define MSR_APIC_ESR					0x828
#define MSR_APIC_SPIV					0x80F
#define MSR_APIC_ICR					0x830
#define MSR_APIC_TASKPRI				0x808
#define MSR_APIC_PROCPRI				0x80A
#define MSR_APIC_IRR					0x820
#define MSR_APIC_ISR					0x810
#define MSR_APIC_TMR					0x818
#define MSR_APIC_TMICT					0x838
#define MSR_APIC_TMCCT					0x839
#define MSR_APIC_TDCR					0x83E
#endif
