$(TEST_DIR)/memory_order.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/memory_order.o: $(TEST_DIR)/memory_order.c $(libcflat)
	@rm -rf  $(cstart.o)
	@rm -rf  fwcfg.o
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o fwcfg.o lib/x86/fwcfg.c
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/mp_initialization.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/mp_initialization.o: $(TEST_DIR)/mp_initialization.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/locked_atomic.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/locked_atomic.o: $(TEST_DIR)/locked_atomic.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/hsi.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/hsi.o: $(TEST_DIR)/hsi.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<
