ifneq ($(FILE_NAME), hsi_16_64_cpumode)
cstart.o = $(TEST_DIR)/cstart64.o
else
cstart.o = $(TEST_DIR)/cstart64_hsi.o
endif

bits = 64
ldarch = elf_x86_64
COMMON_CFLAGS += -mno-red-zone -mno-sse -mno-sse2 -Wa,-mintel64

cflatobjs += lib/x86/setjmp64.o
cflatobjs += lib/x86/intel-iommu.o
cflatobjs += lib/x86/usermode.o
cflatobjs += lib/pci_util.o
cflatobjs += lib/pci_msi.o
cflatobjs += lib/e1000e.o

tests = $(TEST_DIR)/access.flat $(TEST_DIR)/apic.flat \
	  $(TEST_DIR)/emulator.flat $(TEST_DIR)/idt_test.flat \
	  $(TEST_DIR)/xsave.flat $(TEST_DIR)/rmap_chain.flat \
	  $(TEST_DIR)/pcid.flat $(TEST_DIR)/debug.flat \
	  $(TEST_DIR)/ioapic.flat $(TEST_DIR)/memory.flat \
	  $(TEST_DIR)/pku.flat $(TEST_DIR)/hyperv_clock.flat
tests += $(TEST_DIR)/syscall.flat
tests += $(TEST_DIR)/svm.flat
tests += $(TEST_DIR)/vmx.flat
tests += $(TEST_DIR)/tscdeadline_latency.flat
tests += $(TEST_DIR)/intel_iommu.flat
tests += $(TEST_DIR)/vmware_backdoors.flat
tests += $(TEST_DIR)/hyperv_clock.flat
tests += $(TEST_DIR)/smx.flat
tests += $(TEST_DIR)/pt.flat
tests += $(TEST_DIR)/sgx.flat
tests += $(TEST_DIR)/pci.flat

include $(SRCDIR)/$(TEST_DIR)/Makefile.common
