CFLAGS += -I $(TEST_DIR)/ASM

$(TEST_DIR)/init_startup_sample.o: CFLAGS += -DAP_INIT_CHECK=\"init_startup_sample_init.S\"
$(TEST_DIR)/init_startup_sample.o: CFLAGS += -DBP_STARTUP_CHECK=\"init_startup_sample_startup.S\"
$(TEST_DIR)/init_startup_sample.o: CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/init_startup_sample.o: $(TEST_DIR)/init_startup_sample.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/sgx.o: CFLAGS += -DAP_INIT_CHECK=\"sgx_init.S\"
$(TEST_DIR)/sgx.o: CFLAGS += -DBP_STARTUP_CHECK=\"sgx_startup.S\"
$(TEST_DIR)/sgx.o: CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/sgx.o: $(TEST_DIR)/sgx.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<


$(TEST_DIR)/xsave.o: CFLAGS += -DAP_INIT_CHECK=\"init_startup_xsave_init.S\"
$(TEST_DIR)/xsave.o: CFLAGS += -DBP_STARTUP_CHECK=\"init_startup_xsave_startup.S\"
$(TEST_DIR)/xsave.o: CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/xsave.o: $(TEST_DIR)/xsave.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<


$(TEST_DIR)/paging.o: CFLAGS += -DAP_INIT_CHECK=\"paging_init.S\"
$(TEST_DIR)/paging.o: CFLAGS += -DBP_STARTUP_CHECK=\"paging_startup.S\"
$(TEST_DIR)/paging.o: $(TEST_DIR)/paging.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/pmu_fu.o: CFLAGS += -DBP_STARTUP_CHECK=\"pmu_fu_startup.S\"
$(TEST_DIR)/pmu_fu.o: $(TEST_DIR)/pmu_fu.c $(TEST_DIR)/pmu_fu.h
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/branch_profile.o: CFLAGS += -DAP_INIT_CHECK=\"branch_profile_init.S\"
$(TEST_DIR)/branch_profile.o: $(TEST_DIR)/branch_profile.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/device_passthrough.o: CFLAGS += -DAP_INIT_CHECK=\"device_passthrough_init.S\"
$(TEST_DIR)/device_passthrough.o: CFLAGS += -DBP_STARTUP_CHECK=\"device_passthrough_startup.S\"
$(TEST_DIR)/device_passthrough.o: $(TEST_DIR)/device_passthrough.c $(TEST_DIR)/device_passthrough.h 
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/machine_check.o: CFLAGS += -DAP_INIT_CHECK=\"mca_init.S\"
$(TEST_DIR)/machine_check.o: CFLAGS += -DBP_STARTUP_CHECK=\"mca_startup.S\"
$(TEST_DIR)/machine_check.o: $(TEST_DIR)/machine_check.c $(TEST_DIR)/machine_check.h
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/fpu.o: CFLAGS += -DAP_INIT_CHECK=\"fpu_init.S\"
$(TEST_DIR)/fpu.o: CFLAGS += -DBP_STARTUP_CHECK=\"fpu_startup.S\"
$(TEST_DIR)/fpu.o: CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/fpu.o: $(TEST_DIR)/fpu.c $(TEST_DIR)/fpu.h
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/cpumode.o: CFLAGS += -DAP_INIT_CHECK=\"cpumode_ap_init.S\"
$(TEST_DIR)/cpumode.o: CFLAGS += -DBP_STARTUP_CHECK=\"cpumode_bp_startup.S\"
$(TEST_DIR)/cpumode.o: $(TEST_DIR)/cpumode.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/vmx.o: CFLAGS += -DAP_INIT_CHECK=\"vmx_init.S\"
$(TEST_DIR)/vmx.o: CFLAGS += -DBP_STARTUP_CHECK=\"vmx_startup.S\"
$(TEST_DIR)/vmx.o: $(TEST_DIR)/vmx.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/info_leakage.o: CFLAGS += -DAP_INIT_CHECK=\"infoleak_ap_init.S\"
$(TEST_DIR)/info_leakage.o: CFLAGS += -DBP_STARTUP_CHECK=\"infoleak_bp_startup.S\"
$(TEST_DIR)/info_leakage.o: $(TEST_DIR)/info_leakage.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/idle_block.o: CFLAGS += -DAP_INIT_CHECK=\"idle_block_init.S\"
$(TEST_DIR)/idle_block.o: CFLAGS += -DBP_STARTUP_CHECK=\"idle_block_startup.S\"
$(TEST_DIR)/idle_block.o: $(TEST_DIR)/idle_block.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/sse.o: CFLAGS += -DAP_INIT_CHECK=\"sse_init.S\"
$(TEST_DIR)/sse.o: CFLAGS += -DBP_STARTUP_CHECK=\"sse_startup.S\"
$(TEST_DIR)/sse.o: CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/sse.o: $(TEST_DIR)/sse.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/mem_cache.o: CFLAGS += -DAP_INIT_CHECK=\"init_startup_mem_cache_init.S\"
$(TEST_DIR)/mem_cache.o: CFLAGS += -DBP_STARTUP_CHECK=\"init_startup_mem_cache_startup.S\"
$(TEST_DIR)/mem_cache.o: CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/mem_cache.o: $(TEST_DIR)/mem_cache.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<
$(TEST_DIR)/pci.o:CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/pci.o:$(TEST_DIR)/pci.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<
