CFLAGS += -I $(TEST_DIR)/ASM

$(TEST_DIR)/init_startup_sample.o: CFLAGS += -DAP_INIT_CHECK=\"init_startup_sample_init.S\"
$(TEST_DIR)/init_startup_sample.o: CFLAGS += -DBP_STARTUP_CHECK=\"init_startup_sample_startup.S\"
$(TEST_DIR)/init_startup_sample.o: CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/init_startup_sample.o: $(TEST_DIR)/init_startup_sample.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/interrupt.o: CFLAGS += -DAP_INIT_CHECK=\"init_startup_interrupt_init.S\"
$(TEST_DIR)/interrupt.o: CFLAGS += -DBP_STARTUP_CHECK=\"init_startup_interrupt_startup.S\"
$(TEST_DIR)/interrupt.o: CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/interrupt.o: $(TEST_DIR)/interrupt.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/sgx.o: CFLAGS += -DAP_INIT_CHECK=\"sgx_init.S\"
$(TEST_DIR)/sgx.o: CFLAGS += -DBP_STARTUP_CHECK=\"sgx_startup.S\"
$(TEST_DIR)/sgx.o: CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/sgx.o: $(TEST_DIR)/sgx.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<


$(TEST_DIR)/xsave.o: CFLAGS += -DAP_INIT_CHECK=\"init_startup_xsave_init.S\"
$(TEST_DIR)/xsave.o: CFLAGS += -DBP_STARTUP_CHECK=\"init_startup_xsave_startup.S\"
$(TEST_DIR)/xsave.o: CFLAGS += -DAP_UNCHANGED_CHECK
$(TEST_DIR)/xsave.o: $(TEST_DIR)/xsave.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<


$(TEST_DIR)/paging.o: CFLAGS += -DAP_INIT_CHECK=\"paging_init.S\"
$(TEST_DIR)/paging.o: CFLAGS += -DBP_STARTUP_CHECK=\"paging_startup.S\"
$(TEST_DIR)/paging.o: $(TEST_DIR)/paging.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/pmu_fu.o: CFLAGS += -DBP_STARTUP_CHECK=\"pmu_fu_startup.S\"
$(TEST_DIR)/pmu_fu.o: $(TEST_DIR)/pmu_fu.c $(TEST_DIR)/pmu_fu.h
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/branch_profile.o: CFLAGS += -DAP_INIT_CHECK=\"branch_profile_init.S\"
$(TEST_DIR)/branch_profile.o: $(TEST_DIR)/branch_profile.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<
