$(TEST_DIR)/memory_order.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/memory_order.o: $(TEST_DIR)/memory_order.c $(libcflat)
	@rm -rf  $(cstart.o)
	@rm -rf  fwcfg.o
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o fwcfg.o lib/x86/fwcfg.c
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/mp_initialization.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/mp_initialization.o: $(TEST_DIR)/mp_initialization.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/locked_atomic.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/locked_atomic.o: $(TEST_DIR)/locked_atomic.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/hsi.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/hsi.o: $(TEST_DIR)/hsi.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/interrupt.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/interrupt.o: $(TEST_DIR)/interrupt.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/interrupt_mc.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/interrupt_mc.o: $(TEST_DIR)/interrupt_mc.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/hsi_multi_proc_mgmt.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/hsi_multi_proc_mgmt.o: $(TEST_DIR)/hsi_multi_proc_mgmt.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/hsi_gp.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/hsi_gp.o: $(TEST_DIR)/hsi_gp.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/hsi_local_apic.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/hsi_local_apic.o: $(TEST_DIR)/hsi_local_apic.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/sse.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/sse.o: $(TEST_DIR)/sse.c
	@rm -rf  $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/segmentation.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/segmentation.o: $(TEST_DIR)/segmentation.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/avx.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/avx.o: $(TEST_DIR)/avx.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/info_leakage.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/info_leakage.o: $(TEST_DIR)/info_leakage.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/hsi_virtual_spec.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/hsi_virtual_spec.o: $(TEST_DIR)/hsi_virtual_spec.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/rtc.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/rtc.o: $(TEST_DIR)/rtc.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/general_purpose.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/general_purpose.o: $(TEST_DIR)/general_purpose.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/taskmanagement.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/taskmanagement.o: $(TEST_DIR)/taskmanagement.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/tsc.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/tsc.o: $(TEST_DIR)/tsc.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/multiboot.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/multiboot.o: $(TEST_DIR)/multiboot.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/mem_cache.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/mem_cache.o: $(TEST_DIR)/mem_cache.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/idle_block.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/idle_block.o: $(TEST_DIR)/idle_block.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/paging.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/paging.o: $(TEST_DIR)/paging.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<
	
$(TEST_DIR)/local_apic.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/local_apic.o: $(TEST_DIR)/local_apic.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/fpu.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/fpu.o: $(TEST_DIR)/fpu.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/misc_cpuid.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/misc_cpuid.o: $(TEST_DIR)/misc_cpuid.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<

$(TEST_DIR)/misc_msr.o: CFLAGS += -DAP_USE_MAIN
$(TEST_DIR)/misc_msr.o: $(TEST_DIR)/misc_msr.c
	@rm -rf $(cstart.o)
	$(CC) $(CFLAGS) -c -nostdlib -o $(cstart.o) $(cstart.o:.o=.S)
	$(CC) $(CFLAGS) -c -nostdlib -o $@ $<
