#ifndef _SSE_H_
#define _SSE_H_
#define MXCSR_OE_BIT				(1U << 3)

#define INIT_CR4_SAVE_ADDR			(0X7004)
#define INIT_SSE_XSAVE_ADDR		        (0x6500UL)
#define INIT_UNCHANGED_SSE_XSAVE_ADDR	        (0x8500UL)
#define STARTUP_CR4_SAVE_ADDR			(0X7000)
#define STARTUP_SSE_XSAVE_ADDR		        (0x7500UL)
#define STARTUP_SSE64BIT_XSAVE_ADDR	        (0x9000UL)

#define INIT_MSR_FEATURE_CONFIG_LOW_ADDR	(0x700C)
#define INIT_MSR_FEATURE_CONFIG_HIGH_ADDR	(0x7010)
#define STARTUP_MSR_FEATURE_CONFIG_LOW_ADDR	(0x700C)
#define STARTUP_MSR_FEATURE_CONFIG_HIGH_ADDR	(0x7010)
#define MSR_IA32_FEATURE_CONFIG                 (0x13C)


#endif
