#ifndef _TSC_H_
#define _TSC_H_
#define INIT_CR4_ADDR				(0x8008)
#define INIT_TSCADJ_LOW_ADDR		(0x8010)
#define INIT_TSCADJ_HIGH_ADDR		(INIT_TSCADJ_LOW_ADDR+4)
#define INIT_TSCAUX_LOW_ADDR		(INIT_TSCADJ_HIGH_ADDR+4)
#define INIT_TSCAUX_HIGH_ADDR		(INIT_TSCAUX_LOW_ADDR+4)
#define INIT_TSC_LOW_ADDR			(INIT_TSCAUX_HIGH_ADDR+4)
#define INIT_TSC_HIGH_ADDR			(INIT_TSC_LOW_ADDR+4)
#define TSCADJ_UNCHANGE_NEW_VALUE	100000000000ull
#define TSCAUX_UNCHANGE_NEW_VALUE	10ull
#define TSC_UNCHANGE_NEW_VALUE		100000000ull
#define MSR_TSC						0X10
#endif
