name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check_coding_style:
    runs-on: self-hosted
    steps:
      - name: scan
        run: |
          echo "start to check coding style ..."
          cd acrn-unit-test/guest/scripts
          ./checkfolder.sh ../../../acrn-unit-test/	  
  acrn_clang_tidy_job:
    runs-on: self-hosted
    steps:
      - name: scan
        run: |
          echo "start to check coding guideline violations ..."
          pwd
          rm -rf github
          mkdir github && cd github && git clone https://github.com/projectacrn/acrn-unit-test.git
          cp -r ../acrn-unit-test/* acrn-unit-test/
          cd acrn-unit-test/guest/
          make codescan
  build_job:
    runs-on: self-hosted
    steps:
      - name: build
        run: |
          echo "start to build ..."
          pwd
          cd github/acrn-unit-test/guest/
          /opt/acrn-ebtool/docker_runsrs.sh ubuntu:v3.0 "./make_all.sh"
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with: |
          path: github/acrn-unit-test/guest/x86/*.bzimage
                github/acrn-unit-test/guest/x86/*.raw
          retention-days: 21
          if-no-files-found：error
    needs: 
      acrn_clang_tidy_job

  test_lauch_hyperthread:
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          echo "start to test lauching hyperthread ..."
          pwd
          /opt/srsci.sh hyperthread
    needs:
      build_job   

